tools:
  - name: rccl-info
    env:
      NCCL_DEBUG: 'INFO'
      NCCL_DEBUG_TIMESTAMP_LEVELS: 'INFO'
      NCCL_DEBUG_TIMESTAMP_FORMAT: '"%s.%9f "'
      NCCL_DEBUG_SUBSYS: 'COLL'
      # We need to set NCCL_DEBUG_FILE to a unique file per rank, so we use it as a prefix so that it is set per process.
    prefix: 'export NCCL_DEBUG_FILE=tools/rccl-info/\$SLURM_PROCID/rccl-coll.%h.%p.txt; '
    pre-execute: |-
      for proc in $(seq 0 $((SLURM_NTASKS-1))); do
        mkdir -p tools/rccl-info/$proc
      done
