# Dockerfile to run LLAMA models with ROCm
#
# This container is meant to be used for prototyping an automated pipeline and
# collect performance data in our clusters.
#
# It builds and runs everything as root; ownership of any output may need to
# be fixed to ensure they can be read outside the container. If executed
# mounting the /host-home volume (as in docker/run-docker-ubuntu-dev.sh), the
# `fix-host-owner' script can be used to make sure any directory is owned by
# the same user running the container.

FROM rocm/dev-ubuntu-22.04:6.0-complete

ARG CONDA_INSTALLER=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
ARG OMNIPERF_TARBALL=https://github.com/ROCm/omniperf/releases/download/v2.0.0-RC1/omniperf-2.0.0-RC1.tar.gz
ARG OMNITRACE_INSTALLER=https://github.com/ROCm/omnitrace/releases/download/v1.11.2/omnitrace-1.11.2-ubuntu-22.04-ROCm-60000-PAPI-OMPT-Python3.sh
ARG PYTORCH_URL=https://download.pytorch.org/whl/rocm6.0

ARG DEBIAN_FRONTEND=noninteractive

ENV CONDA_DIR=/opt/conda
ENV OMNIPERF_DIR=/opt/omniperf
ENV OMNITRACE_DIR=/opt/omnitrace
ENV PATH="$CONDA_DIR/bin:$OMNIPERF_DIR/bin:$OMNITRACE_DIR/bin:$PATH"
ENV PYTHONPATH="$CONDA_DIR/lib/python3.9/site-packages:$PYTHONPATH"

RUN apt update && \
    apt install -y \
        cmake \
        git \
        vim \
        wget \
        locales \
        glibc-source && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists && \
    locale-gen en_US.UTF-8

WORKDIR /tmp

RUN wget --quiet $CONDA_INSTALLER -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    rm -f /tmp/miniconda.sh

RUN conda update -y conda && \
    conda init && \
    conda install -c conda-forge -y python=3.9

RUN pip install torch torchvision torchaudio --index-url $PYTORCH_URL

RUN git clone https://github.com/ROCm/bitsandbytes.git && \
    cd bitsandbytes && \
    git checkout rocm_enabled && \
    pip install -U pip && \
    pip install -r requirements-dev.txt && \
    cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx90a" -S . && \
    make && \
    pip install . && \
    cd && \
    rm -rf /tmp/bitsandbytes

RUN git clone https://github.com/meta-llama/llama-recipes.git && \
    cd llama-recipes && \
    pip install -U pip setuptools && \
    pip install -e . && \
    cd && \
    rm -rf /tmp/llama-recipes

COPY docker/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && \
    rm -f /tmp/requirements.txt

RUN wget --quiet $OMNIPERF_TARBALL -O /tmp/omniperf.tar.gz && \
    tar xfz /tmp/omniperf.tar.gz -C /tmp && \
    omniperf_basedir=$(basename $OMNIPERF_TARBALL .tar.gz) && \
    cd /tmp/$omniperf_basedir && \
    python3 -m pip install -r requirements.txt && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=${OMNIPERF_DIR} \
        -DPYTHON_DEPS=${CONDA_DIR}/lib/python3.9/site-packages \
        ..  && \
    make install && \
    rm -f /tmp/omniperf.tar.gz && \
    rm -rf /tmp/$omniperf_basedir

RUN wget --quiet $OMNITRACE_INSTALLER -O /tmp/omnitrace-install.sh && \
    mkdir $OMNITRACE_DIR && \
    bash /tmp/omnitrace-install.sh --prefix=$OMNITRACE_DIR --exclude-subdir && \
    rm -f /tmp/omnitrace-install.sh

COPY docker/fix-host-owner.sh /usr/local/bin/fix-host-owner
