cluster:
  name: hpcfund
  models-dir: /work1/models/amd
  shared-dir: /work1/amd/omnihub
  data-dir: /work1/amd/omnihub/data
  results-dir: $WORK/results/omnihub/$SLURM_JOB_ID
  container-platforms:
    - apptainer
  subsets:
    - partition: mi2104x
      gpu: mi210
      num-gpus: 4
      num-nodes: 20
    - partition: mi2508x
      gpu: mi250
      num-gpus: 8
      num-nodes: 8
    - partition: mi3258x
      gpu: mi325
      num-gpus: 8
      num-nodes: 1
    - partition: mi3008x
      gpu: mi300
      num-gpus: 8
      num-nodes: 1
    - partition: mi1008x
      gpu: mi100
      num-gpus: 8
      num-nodes: 6
