cluster:
  name: radha
  models-dir: /shared/omnihub/models
  shared-dir: /home/shared/projs/omnihub
  data-dir: /home/shared/projs/omnihub/data
  results-dir: $HOME/results/omnihub/$SLURM_JOB_ID
  container-platforms:
    - apptainer
    - docker
  subsets:
    - partition: radhadefault
      gpu: mi210
      num-gpus: 4
      num-nodes: 7
    - partition: mi300
      gpu: mi300
      num-gpus: 8
      num-nodes: 1
