entrypoint: applications/hf-finetune/finetune.py
SFTConfig:
  output_dir: ./fine-tuned-models
  num_train_epochs: 3
  per_device_train_batch_size: 2
  bf16: true
  gradient_checkpointing_kwargs:
    use_reentrant: true
  dataset_text_field: text
  # dont save checkpoints
  save_strategy: "no"
  fsdp: hybrid_shard
DataTrainingArguments:
  dataset_name: mlabonne/guanaco-llama2-1k
  dataset_split_test_size: 0.1
LoRAArguments:
  lora_alpha: 15
  lora_dropout: 0.1
  r: 64
  bias: none
  task_type: CAUSAL_LM
  target_modules: all-linear
ModelArguments:
  pretrained_model_name_or_path: Meta-Llama-3.1-8B-Instruct-safetensors

# Comment out for now because ROCm support for BitsAndBytes is not stable
# BitsAndBytesConfigDataclass:
#   load_in_4bit: true
#   bnb_4bit_quant_type: nf4
#   bnb_4bit_compute_dtype: bfloat16
#   bnb_4bit_use_double_quant: true
#   load_in_8bit: false
#   quant_method: bitsandbytes
