# Primus Pretrain Configuration for Omnihub
# This config demonstrates how to run Primus pretraining through the Omnihub framework
entrypoint: applications/primus-pretrain/pretrain_wrapper.py
# Path to Primus installation
primus_path: /app/Primus
# Path to experiment config file (REQUIRED)
# This should point to a Primus experiment YAML file
exp_config: /app/Primus/examples/megatron/configs/MI300X/llama3.1_8B-BF16-pretrain.yaml
# Overrides for the experiment config. These values will take precedence over those in the exp_config file.
# The purpose of these overrides is for OmniHub to be able to sweep over different values and modify the
# experiment config without the user having to create multiple experiment config files for each run.
work_group: amd
user_name: root
exp_name: llama3.1_8B-pretrain
workspace: ./output
modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    # model to run
    model: llama3.1_8B.yaml
    overrides:
      # log
      wandb_project: Primus_DeepSeek_Pretrain
      # disable_wandb: false
      # disable_tensorboard: false
      stderr_sink_level: DEBUG
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50
      train_iters: 50
      micro_batch_size: 2
      global_batch_size: 128
      seq_length: 8192
      max_position_embeddings: 8192
      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters:
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6
      # parallel
      tensor_model_parallel_size:
        - 1
        - 8
      pipeline_model_parallel_size: 1
      expert_model_parallel_size:
        - 1
        - 8
      overlap_grad_reduce:
        - true
        - false
      overlap_param_gather:
        - true
        - false
      gradient_accumulation_fusion:
        - true
        - false
      # data
      mock_data: true
      train_data_path:
      valid_data_path:
      test_data_path:
      # ckpt
      finetune: false
      auto_continue_train: false
      load:
      no_load_optim:
      no_load_rng:
      save:
      save_interval: 20000
      no_save_optim:
      no_save_rng:
      disable_last_saving: true
      ckpt_format: torch
      # Turbo
      enable_primus_turbo: true
      use_turbo_attention: false
      use_turbo_grouped_mlp: false

# Cross entropy flags
# cross_entropy_fusion_impl: "te"
# cross_entropy_loss_fusion: true
