name: Syncup Docker and Apptainer Images
run-name: syncup by ${{ github.actor }}

on:
  pull_request:
    branches: [main]
    paths:
    - 'docker/Dockerfile*'
    - '.github/workflows/image_sync.yml'

jobs:
  syncup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install spython

      - name: Convert Dockerfile with Apptainer definition file
        run: |
          for i in docker/Dockerfile*; do \
            base_name=${i#*/}; \
            echo "spython recipe ${i} > apptainer/${base_name/Dockerfile/omnihub}.def"; \
            spython recipe ${i} > apptainer/${base_name/Dockerfile/omnihub}.def; \
          done

      - name: Commit changes (if necessary)
        run: |
          git config --global user.name 'docker-apptainer-syncup-bot'
          git config --global user.email 'bot@no-reply.com'
          git add apptainer/*.def
          git diff-index --cached --quiet HEAD apptainer/*.def
          retVal=$?
          if [ $retVal -ne 0 ]; then
            git commit -m 'Converted Dockerfiles to corresponding Apptainer definition files'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
